version: '3.4'

x-logging:
  logging: &logging
    options:
      max-size: 50m

services:
  react:
    hostname: react
    image: local/react
    volumes:
      - ./src:/usr/app/src:rw
      - ./env:/usr/app/env:ro
      - .:/external:rw
    ports:
      - '3500:3500'
      - '4000:4000'
      - '19000-19009:19000-19009'
    extra_hosts:
      - 'host.docker.internal:$DOCKER_HOST_IP'
    logging: *logging
    command: sleep infinity

  react-dynamic:
    hostname: react
    build:
      context: .
      dockerfile: docker/react.dockerfile
    volumes:
      - .:/usr/app:rw
    ports:
      - '3500:3500'
      - '4000:4000'
      - '19000-19009:19000-19009'
    extra_hosts:
      - 'host.docker.internal:$DOCKER_HOST_IP'
    logging: *logging
    command: sleep infinity
